// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

/**
 * A completed PDF form, based on the results of a questionnaire
 */
public class CompleteForm extends pdf_exporter.proxies.PDFDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.CompleteForm";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		CompleteForm_BlankForm("PDF_Exporter.CompleteForm_BlankForm");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CompleteForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.CompleteForm"));
	}

	protected CompleteForm(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject completeFormMendixObject)
	{
		super(context, completeFormMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.CompleteForm", completeFormMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.CompleteForm");
	}

	/**
	 * @deprecated Use 'CompleteForm.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.CompleteForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.CompleteForm.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.CompleteForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.CompleteForm(context, mendixObject);
	}

	public static pdf_exporter.proxies.CompleteForm load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.CompleteForm.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.CompleteForm> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.CompleteForm> result = new java.util.ArrayList<pdf_exporter.proxies.CompleteForm>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.CompleteForm" + xpathConstraint))
			result.add(pdf_exporter.proxies.CompleteForm.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CompleteForm_BlankForm
	 */
	public final pdf_exporter.proxies.PDFTemplate getCompleteForm_BlankForm() throws com.mendix.core.CoreException
	{
		return getCompleteForm_BlankForm(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteForm_BlankForm
	 */
	public final pdf_exporter.proxies.PDFTemplate getCompleteForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.PDFTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CompleteForm_BlankForm.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.PDFTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CompleteForm_BlankForm
	 * @param completeform_blankform
	 */
	public final void setCompleteForm_BlankForm(pdf_exporter.proxies.PDFTemplate completeform_blankform)
	{
		setCompleteForm_BlankForm(getContext(), completeform_blankform);
	}

	/**
	 * Set value of CompleteForm_BlankForm
	 * @param context
	 * @param completeform_blankform
	 */
	public final void setCompleteForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDFTemplate completeform_blankform)
	{
		if (completeform_blankform == null)
			getMendixObject().setValue(context, MemberNames.CompleteForm_BlankForm.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CompleteForm_BlankForm.toString(), completeform_blankform.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.CompleteForm that = (pdf_exporter.proxies.CompleteForm) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.CompleteForm";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
