// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

/**
 * A completed PDF form, based on the results of a questionnaire
 */
public class FieldNamesForm extends pdf_exporter.proxies.PDFDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.FieldNamesForm";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		FieldNamesForm_BlankForm("PDF_Exporter.FieldNamesForm_BlankForm");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FieldNamesForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.FieldNamesForm"));
	}

	protected FieldNamesForm(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fieldNamesFormMendixObject)
	{
		super(context, fieldNamesFormMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.FieldNamesForm", fieldNamesFormMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.FieldNamesForm");
	}

	/**
	 * @deprecated Use 'FieldNamesForm.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.FieldNamesForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.FieldNamesForm.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.FieldNamesForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.FieldNamesForm(context, mendixObject);
	}

	public static pdf_exporter.proxies.FieldNamesForm load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.FieldNamesForm.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.FieldNamesForm> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.FieldNamesForm> result = new java.util.ArrayList<pdf_exporter.proxies.FieldNamesForm>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.FieldNamesForm" + xpathConstraint))
			result.add(pdf_exporter.proxies.FieldNamesForm.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FieldNamesForm_BlankForm
	 */
	public final pdf_exporter.proxies.PDFTemplate getFieldNamesForm_BlankForm() throws com.mendix.core.CoreException
	{
		return getFieldNamesForm_BlankForm(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldNamesForm_BlankForm
	 */
	public final pdf_exporter.proxies.PDFTemplate getFieldNamesForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.PDFTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FieldNamesForm_BlankForm.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.PDFTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FieldNamesForm_BlankForm
	 * @param fieldnamesform_blankform
	 */
	public final void setFieldNamesForm_BlankForm(pdf_exporter.proxies.PDFTemplate fieldnamesform_blankform)
	{
		setFieldNamesForm_BlankForm(getContext(), fieldnamesform_blankform);
	}

	/**
	 * Set value of FieldNamesForm_BlankForm
	 * @param context
	 * @param fieldnamesform_blankform
	 */
	public final void setFieldNamesForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDFTemplate fieldnamesform_blankform)
	{
		if (fieldnamesform_blankform == null)
			getMendixObject().setValue(context, MemberNames.FieldNamesForm_BlankForm.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FieldNamesForm_BlankForm.toString(), fieldnamesform_blankform.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.FieldNamesForm that = (pdf_exporter.proxies.FieldNamesForm) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.FieldNamesForm";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
