// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public class MxXPath
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxXPathMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.MxXPath";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RetrieveType("RetrieveType"),
		SubVisible("SubVisible"),
		PrimitiveType("PrimitiveType"),
		DateFormat("DateFormat"),
		NumberFormat("NumberFormat"),
		BooleanTrue("BooleanTrue"),
		BooleanFalse("BooleanFalse"),
		MxXPath_ParentMxXPath("PDF_Exporter.MxXPath_ParentMxXPath"),
		PDFField_MxXPath("PDF_Exporter.PDFField_MxXPath"),
		ChildMxXPath_MxXPath("PDF_Exporter.ChildMxXPath_MxXPath"),
		MxXPath_MxObjectMember("PDF_Exporter.MxXPath_MxObjectMember"),
		MxXPath_MxObjectReference("PDF_Exporter.MxXPath_MxObjectReference"),
		MxXPath_MxObjectType("PDF_Exporter.MxXPath_MxObjectType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxXPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.MxXPath"));
	}

	protected MxXPath(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxXPathMendixObject)
	{
		if (mxXPathMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.MxXPath", mxXPathMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.MxXPath");

		this.mxXPathMendixObject = mxXPathMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxXPath.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.MxXPath initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.MxXPath.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.MxXPath initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.MxXPath(context, mendixObject);
	}

	public static pdf_exporter.proxies.MxXPath load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.MxXPath.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.MxXPath> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.MxXPath> result = new java.util.ArrayList<pdf_exporter.proxies.MxXPath>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.MxXPath" + xpathConstraint))
			result.add(pdf_exporter.proxies.MxXPath.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of RetrieveType
	 * @param retrievetype
	 */
	public final pdf_exporter.proxies.RetrieveAction getRetrieveType()
	{
		return getRetrieveType(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveType
	 */
	public final pdf_exporter.proxies.RetrieveAction getRetrieveType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RetrieveType.toString());
		if (obj == null)
			return null;

		return pdf_exporter.proxies.RetrieveAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RetrieveType
	 * @param retrievetype
	 */
	public final void setRetrieveType(pdf_exporter.proxies.RetrieveAction retrievetype)
	{
		setRetrieveType(getContext(), retrievetype);
	}

	/**
	 * Set value of RetrieveType
	 * @param context
	 * @param retrievetype
	 */
	public final void setRetrieveType(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.RetrieveAction retrievetype)
	{
		if (retrievetype != null)
			getMendixObject().setValue(context, MemberNames.RetrieveType.toString(), retrievetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RetrieveType.toString(), null);
	}

	/**
	 * @return value of SubVisible
	 */
	public final Boolean getSubVisible()
	{
		return getSubVisible(getContext());
	}

	/**
	 * @param context
	 * @return value of SubVisible
	 */
	public final Boolean getSubVisible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.SubVisible.toString());
	}

	/**
	 * Set value of SubVisible
	 * @param subvisible
	 */
	public final void setSubVisible(Boolean subvisible)
	{
		setSubVisible(getContext(), subvisible);
	}

	/**
	 * Set value of SubVisible
	 * @param context
	 * @param subvisible
	 */
	public final void setSubVisible(com.mendix.systemwideinterfaces.core.IContext context, Boolean subvisible)
	{
		getMendixObject().setValue(context, MemberNames.SubVisible.toString(), subvisible);
	}

	/**
	 * Set value of PrimitiveType
	 * @param primitivetype
	 */
	public final mxmodelreflection.proxies.PrimitiveTypes getPrimitiveType()
	{
		return getPrimitiveType(getContext());
	}

	/**
	 * @param context
	 * @return value of PrimitiveType
	 */
	public final mxmodelreflection.proxies.PrimitiveTypes getPrimitiveType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PrimitiveType.toString());
		if (obj == null)
			return null;

		return mxmodelreflection.proxies.PrimitiveTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PrimitiveType
	 * @param primitivetype
	 */
	public final void setPrimitiveType(mxmodelreflection.proxies.PrimitiveTypes primitivetype)
	{
		setPrimitiveType(getContext(), primitivetype);
	}

	/**
	 * Set value of PrimitiveType
	 * @param context
	 * @param primitivetype
	 */
	public final void setPrimitiveType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.PrimitiveTypes primitivetype)
	{
		if (primitivetype != null)
			getMendixObject().setValue(context, MemberNames.PrimitiveType.toString(), primitivetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.PrimitiveType.toString(), null);
	}

	/**
	 * @return value of DateFormat
	 */
	public final String getDateFormat()
	{
		return getDateFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFormat
	 */
	public final String getDateFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DateFormat.toString());
	}

	/**
	 * Set value of DateFormat
	 * @param dateformat
	 */
	public final void setDateFormat(String dateformat)
	{
		setDateFormat(getContext(), dateformat);
	}

	/**
	 * Set value of DateFormat
	 * @param context
	 * @param dateformat
	 */
	public final void setDateFormat(com.mendix.systemwideinterfaces.core.IContext context, String dateformat)
	{
		getMendixObject().setValue(context, MemberNames.DateFormat.toString(), dateformat);
	}

	/**
	 * @return value of NumberFormat
	 */
	public final String getNumberFormat()
	{
		return getNumberFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberFormat
	 */
	public final String getNumberFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.NumberFormat.toString());
	}

	/**
	 * Set value of NumberFormat
	 * @param numberformat
	 */
	public final void setNumberFormat(String numberformat)
	{
		setNumberFormat(getContext(), numberformat);
	}

	/**
	 * Set value of NumberFormat
	 * @param context
	 * @param numberformat
	 */
	public final void setNumberFormat(com.mendix.systemwideinterfaces.core.IContext context, String numberformat)
	{
		getMendixObject().setValue(context, MemberNames.NumberFormat.toString(), numberformat);
	}

	/**
	 * @return value of BooleanTrue
	 */
	public final String getBooleanTrue()
	{
		return getBooleanTrue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanTrue
	 */
	public final String getBooleanTrue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.BooleanTrue.toString());
	}

	/**
	 * Set value of BooleanTrue
	 * @param booleantrue
	 */
	public final void setBooleanTrue(String booleantrue)
	{
		setBooleanTrue(getContext(), booleantrue);
	}

	/**
	 * Set value of BooleanTrue
	 * @param context
	 * @param booleantrue
	 */
	public final void setBooleanTrue(com.mendix.systemwideinterfaces.core.IContext context, String booleantrue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanTrue.toString(), booleantrue);
	}

	/**
	 * @return value of BooleanFalse
	 */
	public final String getBooleanFalse()
	{
		return getBooleanFalse(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanFalse
	 */
	public final String getBooleanFalse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.BooleanFalse.toString());
	}

	/**
	 * Set value of BooleanFalse
	 * @param booleanfalse
	 */
	public final void setBooleanFalse(String booleanfalse)
	{
		setBooleanFalse(getContext(), booleanfalse);
	}

	/**
	 * Set value of BooleanFalse
	 * @param context
	 * @param booleanfalse
	 */
	public final void setBooleanFalse(com.mendix.systemwideinterfaces.core.IContext context, String booleanfalse)
	{
		getMendixObject().setValue(context, MemberNames.BooleanFalse.toString(), booleanfalse);
	}

	/**
	 * @return value of MxXPath_ParentMxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getMxXPath_ParentMxXPath() throws com.mendix.core.CoreException
	{
		return getMxXPath_ParentMxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_ParentMxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getMxXPath_ParentMxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_ParentMxXPath.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_ParentMxXPath
	 * @param mxxpath_parentmxxpath
	 */
	public final void setMxXPath_ParentMxXPath(pdf_exporter.proxies.MxXPath mxxpath_parentmxxpath)
	{
		setMxXPath_ParentMxXPath(getContext(), mxxpath_parentmxxpath);
	}

	/**
	 * Set value of MxXPath_ParentMxXPath
	 * @param context
	 * @param mxxpath_parentmxxpath
	 */
	public final void setMxXPath_ParentMxXPath(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.MxXPath mxxpath_parentmxxpath)
	{
		if (mxxpath_parentmxxpath == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_ParentMxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_ParentMxXPath.toString(), mxxpath_parentmxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of PDFField_MxXPath
	 */
	public final pdf_exporter.proxies.PDFField getPDFField_MxXPath() throws com.mendix.core.CoreException
	{
		return getPDFField_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFField_MxXPath
	 */
	public final pdf_exporter.proxies.PDFField getPDFField_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.PDFField result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFField_MxXPath.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.PDFField.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFField_MxXPath
	 * @param pdffield_mxxpath
	 */
	public final void setPDFField_MxXPath(pdf_exporter.proxies.PDFField pdffield_mxxpath)
	{
		setPDFField_MxXPath(getContext(), pdffield_mxxpath);
	}

	/**
	 * Set value of PDFField_MxXPath
	 * @param context
	 * @param pdffield_mxxpath
	 */
	public final void setPDFField_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDFField pdffield_mxxpath)
	{
		if (pdffield_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.PDFField_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFField_MxXPath.toString(), pdffield_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of ChildMxXPath_MxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getChildMxXPath_MxXPath() throws com.mendix.core.CoreException
	{
		return getChildMxXPath_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of ChildMxXPath_MxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getChildMxXPath_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChildMxXPath_MxXPath.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChildMxXPath_MxXPath
	 * @param childmxxpath_mxxpath
	 */
	public final void setChildMxXPath_MxXPath(pdf_exporter.proxies.MxXPath childmxxpath_mxxpath)
	{
		setChildMxXPath_MxXPath(getContext(), childmxxpath_mxxpath);
	}

	/**
	 * Set value of ChildMxXPath_MxXPath
	 * @param context
	 * @param childmxxpath_mxxpath
	 */
	public final void setChildMxXPath_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.MxXPath childmxxpath_mxxpath)
	{
		if (childmxxpath_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.ChildMxXPath_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChildMxXPath_MxXPath.toString(), childmxxpath_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getMxXPath_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getMxXPath_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectMember
	 * @param mxxpath_mxobjectmember
	 */
	public final void setMxXPath_MxObjectMember(mxmodelreflection.proxies.MxObjectMember mxxpath_mxobjectmember)
	{
		setMxXPath_MxObjectMember(getContext(), mxxpath_mxobjectmember);
	}

	/**
	 * Set value of MxXPath_MxObjectMember
	 * @param context
	 * @param mxxpath_mxobjectmember
	 */
	public final void setMxXPath_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember mxxpath_mxobjectmember)
	{
		if (mxxpath_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectMember.toString(), mxxpath_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getMxXPath_MxObjectReference() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectReference(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getMxXPath_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectReference.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectReference
	 * @param mxxpath_mxobjectreference
	 */
	public final void setMxXPath_MxObjectReference(mxmodelreflection.proxies.MxObjectReference mxxpath_mxobjectreference)
	{
		setMxXPath_MxObjectReference(getContext(), mxxpath_mxobjectreference);
	}

	/**
	 * Set value of MxXPath_MxObjectReference
	 * @param context
	 * @param mxxpath_mxobjectreference
	 */
	public final void setMxXPath_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference mxxpath_mxobjectreference)
	{
		if (mxxpath_mxobjectreference == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectReference.toString(), mxxpath_mxobjectreference.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxXPath_MxObjectType() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxXPath_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectType
	 * @param mxxpath_mxobjecttype
	 */
	public final void setMxXPath_MxObjectType(mxmodelreflection.proxies.MxObjectType mxxpath_mxobjecttype)
	{
		setMxXPath_MxObjectType(getContext(), mxxpath_mxobjecttype);
	}

	/**
	 * Set value of MxXPath_MxObjectType
	 * @param context
	 * @param mxxpath_mxobjecttype
	 */
	public final void setMxXPath_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType mxxpath_mxobjecttype)
	{
		if (mxxpath_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectType.toString(), mxxpath_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxXPathMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.MxXPath that = (pdf_exporter.proxies.MxXPath) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.MxXPath";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
