// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public enum PDF_Field_MappingType
{
	Dynamic(new String[][] { new String[] { "en_US", "Dynamic" } }),
	_Static(new String[][] { new String[] { "en_US", "Static" } });

	private java.util.Map<String,String> captions;

	private PDF_Field_MappingType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
