// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public enum PDF_FormType
{
	Text(new String[][] { new String[] { "en_US", "Text" } }),
	Bullet_List(new String[][] { new String[] { "en_US", "Bullet_List" } }),
	Checkbox(new String[][] { new String[] { "en_US", "Checkbox" } }),
	Bullet(new String[][] { new String[] { "en_US", "Bullet" } });

	private java.util.Map<String,String> captions;

	private PDF_FormType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
