// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public class PDFChoice
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pDFChoiceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.PDFChoice";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OptionValue("OptionValue"),
		PDFChoice_PDFField("PDF_Exporter.PDFChoice_PDFField");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PDFChoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.PDFChoice"));
	}

	protected PDFChoice(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pDFChoiceMendixObject)
	{
		if (pDFChoiceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.PDFChoice", pDFChoiceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.PDFChoice");

		this.pDFChoiceMendixObject = pDFChoiceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PDFChoice.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.PDFChoice initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.PDFChoice.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.PDFChoice initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.PDFChoice(context, mendixObject);
	}

	public static pdf_exporter.proxies.PDFChoice load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.PDFChoice.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.PDFChoice> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.PDFChoice> result = new java.util.ArrayList<pdf_exporter.proxies.PDFChoice>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.PDFChoice" + xpathConstraint))
			result.add(pdf_exporter.proxies.PDFChoice.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OptionValue
	 */
	public final String getOptionValue()
	{
		return getOptionValue(getContext());
	}

	/**
	 * @param context
	 * @return value of OptionValue
	 */
	public final String getOptionValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.OptionValue.toString());
	}

	/**
	 * Set value of OptionValue
	 * @param optionvalue
	 */
	public final void setOptionValue(String optionvalue)
	{
		setOptionValue(getContext(), optionvalue);
	}

	/**
	 * Set value of OptionValue
	 * @param context
	 * @param optionvalue
	 */
	public final void setOptionValue(com.mendix.systemwideinterfaces.core.IContext context, String optionvalue)
	{
		getMendixObject().setValue(context, MemberNames.OptionValue.toString(), optionvalue);
	}

	/**
	 * @return value of PDFChoice_PDFField
	 */
	public final pdf_exporter.proxies.PDFField getPDFChoice_PDFField() throws com.mendix.core.CoreException
	{
		return getPDFChoice_PDFField(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFChoice_PDFField
	 */
	public final pdf_exporter.proxies.PDFField getPDFChoice_PDFField(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.PDFField result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFChoice_PDFField.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.PDFField.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFChoice_PDFField
	 * @param pdfchoice_pdffield
	 */
	public final void setPDFChoice_PDFField(pdf_exporter.proxies.PDFField pdfchoice_pdffield)
	{
		setPDFChoice_PDFField(getContext(), pdfchoice_pdffield);
	}

	/**
	 * Set value of PDFChoice_PDFField
	 * @param context
	 * @param pdfchoice_pdffield
	 */
	public final void setPDFChoice_PDFField(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDFField pdfchoice_pdffield)
	{
		if (pdfchoice_pdffield == null)
			getMendixObject().setValue(context, MemberNames.PDFChoice_PDFField.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFChoice_PDFField.toString(), pdfchoice_pdffield.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pDFChoiceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.PDFChoice that = (pdf_exporter.proxies.PDFChoice) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.PDFChoice";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
