// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public class PDFDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.PDFDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PDFDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.PDFDocument"));
	}

	protected PDFDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pDFDocumentMendixObject)
	{
		super(context, pDFDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.PDFDocument", pDFDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.PDFDocument");
	}

	/**
	 * @deprecated Use 'PDFDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.PDFDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.PDFDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.PDFDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("PDF_Exporter.CompleteForm", mendixObject.getType()))
			return pdf_exporter.proxies.CompleteForm.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("PDF_Exporter.FieldNamesForm", mendixObject.getType()))
			return pdf_exporter.proxies.FieldNamesForm.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("PDF_Exporter.PDFTemplate", mendixObject.getType()))
			return pdf_exporter.proxies.PDFTemplate.initialize(context, mendixObject);

		return new pdf_exporter.proxies.PDFDocument(context, mendixObject);
	}

	public static pdf_exporter.proxies.PDFDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.PDFDocument.initialize(context, mendixObject);
	}

	public static java.util.List<? extends pdf_exporter.proxies.PDFDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.PDFDocument> result = new java.util.ArrayList<pdf_exporter.proxies.PDFDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.PDFDocument" + xpathConstraint))
			result.add(pdf_exporter.proxies.PDFDocument.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.PDFDocument that = (pdf_exporter.proxies.PDFDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.PDFDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
