// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public class PDFField
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pDFFieldMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.PDFField";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AutoNum("AutoNum"),
		Name("Name"),
		Value("Value"),
		FieldType("FieldType"),
		ParentName("ParentName"),
		Length("Length"),
		Page("Page"),
		AddendumValue("AddendumValue"),
		MappingType("MappingType"),
		MappedAttribute("MappedAttribute"),
		PDFField_PDFDoc("PDF_Exporter.PDFField_PDFDoc"),
		PDFField_MxXPath("PDF_Exporter.PDFField_MxXPath"),
		PDFField_MxObjectMember("PDF_Exporter.PDFField_MxObjectMember"),
		PDFField_MxObjectType("PDF_Exporter.PDFField_MxObjectType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PDFField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.PDFField"));
	}

	protected PDFField(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pDFFieldMendixObject)
	{
		if (pDFFieldMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.PDFField", pDFFieldMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.PDFField");

		this.pDFFieldMendixObject = pDFFieldMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PDFField.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.PDFField initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.PDFField.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.PDFField initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.PDFField(context, mendixObject);
	}

	public static pdf_exporter.proxies.PDFField load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.PDFField.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.PDFField> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.PDFField> result = new java.util.ArrayList<pdf_exporter.proxies.PDFField>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.PDFField" + xpathConstraint))
			result.add(pdf_exporter.proxies.PDFField.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AutoNum
	 */
	public final Long getAutoNum()
	{
		return getAutoNum(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNum
	 */
	public final Long getAutoNum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.AutoNum.toString());
	}

	/**
	 * Set value of AutoNum
	 * @param autonum
	 */
	public final void setAutoNum(Long autonum)
	{
		setAutoNum(getContext(), autonum);
	}

	/**
	 * Set value of AutoNum
	 * @param context
	 * @param autonum
	 */
	public final void setAutoNum(com.mendix.systemwideinterfaces.core.IContext context, Long autonum)
	{
		getMendixObject().setValue(context, MemberNames.AutoNum.toString(), autonum);
	}

	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final pdf_exporter.proxies.PDF_FormType getFieldType()
	{
		return getFieldType(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldType
	 */
	public final pdf_exporter.proxies.PDF_FormType getFieldType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FieldType.toString());
		if (obj == null)
			return null;

		return pdf_exporter.proxies.PDF_FormType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final void setFieldType(pdf_exporter.proxies.PDF_FormType fieldtype)
	{
		setFieldType(getContext(), fieldtype);
	}

	/**
	 * Set value of FieldType
	 * @param context
	 * @param fieldtype
	 */
	public final void setFieldType(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDF_FormType fieldtype)
	{
		if (fieldtype != null)
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), fieldtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), null);
	}

	/**
	 * @return value of ParentName
	 */
	public final String getParentName()
	{
		return getParentName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentName
	 */
	public final String getParentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ParentName.toString());
	}

	/**
	 * Set value of ParentName
	 * @param parentname
	 */
	public final void setParentName(String parentname)
	{
		setParentName(getContext(), parentname);
	}

	/**
	 * Set value of ParentName
	 * @param context
	 * @param parentname
	 */
	public final void setParentName(com.mendix.systemwideinterfaces.core.IContext context, String parentname)
	{
		getMendixObject().setValue(context, MemberNames.ParentName.toString(), parentname);
	}

	/**
	 * @return value of Length
	 */
	public final Integer getLength()
	{
		return getLength(getContext());
	}

	/**
	 * @param context
	 * @return value of Length
	 */
	public final Integer getLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Length.toString());
	}

	/**
	 * Set value of Length
	 * @param length
	 */
	public final void setLength(Integer length)
	{
		setLength(getContext(), length);
	}

	/**
	 * Set value of Length
	 * @param context
	 * @param length
	 */
	public final void setLength(com.mendix.systemwideinterfaces.core.IContext context, Integer length)
	{
		getMendixObject().setValue(context, MemberNames.Length.toString(), length);
	}

	/**
	 * @return value of Page
	 */
	public final Integer getPage()
	{
		return getPage(getContext());
	}

	/**
	 * @param context
	 * @return value of Page
	 */
	public final Integer getPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Page.toString());
	}

	/**
	 * Set value of Page
	 * @param page
	 */
	public final void setPage(Integer page)
	{
		setPage(getContext(), page);
	}

	/**
	 * Set value of Page
	 * @param context
	 * @param page
	 */
	public final void setPage(com.mendix.systemwideinterfaces.core.IContext context, Integer page)
	{
		getMendixObject().setValue(context, MemberNames.Page.toString(), page);
	}

	/**
	 * @return value of AddendumValue
	 */
	public final String getAddendumValue()
	{
		return getAddendumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of AddendumValue
	 */
	public final String getAddendumValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AddendumValue.toString());
	}

	/**
	 * Set value of AddendumValue
	 * @param addendumvalue
	 */
	public final void setAddendumValue(String addendumvalue)
	{
		setAddendumValue(getContext(), addendumvalue);
	}

	/**
	 * Set value of AddendumValue
	 * @param context
	 * @param addendumvalue
	 */
	public final void setAddendumValue(com.mendix.systemwideinterfaces.core.IContext context, String addendumvalue)
	{
		getMendixObject().setValue(context, MemberNames.AddendumValue.toString(), addendumvalue);
	}

	/**
	 * Set value of MappingType
	 * @param mappingtype
	 */
	public final pdf_exporter.proxies.PDF_Field_MappingType getMappingType()
	{
		return getMappingType(getContext());
	}

	/**
	 * @param context
	 * @return value of MappingType
	 */
	public final pdf_exporter.proxies.PDF_Field_MappingType getMappingType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MappingType.toString());
		if (obj == null)
			return null;

		return pdf_exporter.proxies.PDF_Field_MappingType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MappingType
	 * @param mappingtype
	 */
	public final void setMappingType(pdf_exporter.proxies.PDF_Field_MappingType mappingtype)
	{
		setMappingType(getContext(), mappingtype);
	}

	/**
	 * Set value of MappingType
	 * @param context
	 * @param mappingtype
	 */
	public final void setMappingType(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDF_Field_MappingType mappingtype)
	{
		if (mappingtype != null)
			getMendixObject().setValue(context, MemberNames.MappingType.toString(), mappingtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.MappingType.toString(), null);
	}

	/**
	 * @return value of MappedAttribute
	 */
	public final String getMappedAttribute()
	{
		return getMappedAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of MappedAttribute
	 */
	public final String getMappedAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.MappedAttribute.toString());
	}

	/**
	 * Set value of MappedAttribute
	 * @param mappedattribute
	 */
	public final void setMappedAttribute(String mappedattribute)
	{
		setMappedAttribute(getContext(), mappedattribute);
	}

	/**
	 * Set value of MappedAttribute
	 * @param context
	 * @param mappedattribute
	 */
	public final void setMappedAttribute(com.mendix.systemwideinterfaces.core.IContext context, String mappedattribute)
	{
		getMendixObject().setValue(context, MemberNames.MappedAttribute.toString(), mappedattribute);
	}

	/**
	 * @return value of PDFField_PDFDoc
	 */
	public final pdf_exporter.proxies.PDFDocument getPDFField_PDFDoc() throws com.mendix.core.CoreException
	{
		return getPDFField_PDFDoc(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFField_PDFDoc
	 */
	public final pdf_exporter.proxies.PDFDocument getPDFField_PDFDoc(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.PDFDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFField_PDFDoc.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.PDFDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFField_PDFDoc
	 * @param pdffield_pdfdoc
	 */
	public final void setPDFField_PDFDoc(pdf_exporter.proxies.PDFDocument pdffield_pdfdoc)
	{
		setPDFField_PDFDoc(getContext(), pdffield_pdfdoc);
	}

	/**
	 * Set value of PDFField_PDFDoc
	 * @param context
	 * @param pdffield_pdfdoc
	 */
	public final void setPDFField_PDFDoc(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.PDFDocument pdffield_pdfdoc)
	{
		if (pdffield_pdfdoc == null)
			getMendixObject().setValue(context, MemberNames.PDFField_PDFDoc.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFField_PDFDoc.toString(), pdffield_pdfdoc.getMendixObject().getId());
	}

	/**
	 * @return value of PDFField_MxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getPDFField_MxXPath() throws com.mendix.core.CoreException
	{
		return getPDFField_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFField_MxXPath
	 */
	public final pdf_exporter.proxies.MxXPath getPDFField_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFField_MxXPath.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFField_MxXPath
	 * @param pdffield_mxxpath
	 */
	public final void setPDFField_MxXPath(pdf_exporter.proxies.MxXPath pdffield_mxxpath)
	{
		setPDFField_MxXPath(getContext(), pdffield_mxxpath);
	}

	/**
	 * Set value of PDFField_MxXPath
	 * @param context
	 * @param pdffield_mxxpath
	 */
	public final void setPDFField_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.MxXPath pdffield_mxxpath)
	{
		if (pdffield_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.PDFField_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFField_MxXPath.toString(), pdffield_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of PDFField_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getPDFField_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getPDFField_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFField_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getPDFField_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFField_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFField_MxObjectMember
	 * @param pdffield_mxobjectmember
	 */
	public final void setPDFField_MxObjectMember(mxmodelreflection.proxies.MxObjectMember pdffield_mxobjectmember)
	{
		setPDFField_MxObjectMember(getContext(), pdffield_mxobjectmember);
	}

	/**
	 * Set value of PDFField_MxObjectMember
	 * @param context
	 * @param pdffield_mxobjectmember
	 */
	public final void setPDFField_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember pdffield_mxobjectmember)
	{
		if (pdffield_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.PDFField_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFField_MxObjectMember.toString(), pdffield_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return value of PDFField_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getPDFField_MxObjectType() throws com.mendix.core.CoreException
	{
		return getPDFField_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFField_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getPDFField_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFField_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFField_MxObjectType
	 * @param pdffield_mxobjecttype
	 */
	public final void setPDFField_MxObjectType(mxmodelreflection.proxies.MxObjectType pdffield_mxobjecttype)
	{
		setPDFField_MxObjectType(getContext(), pdffield_mxobjecttype);
	}

	/**
	 * Set value of PDFField_MxObjectType
	 * @param context
	 * @param pdffield_mxobjecttype
	 */
	public final void setPDFField_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType pdffield_mxobjecttype)
	{
		if (pdffield_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.PDFField_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFField_MxObjectType.toString(), pdffield_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pDFFieldMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.PDFField that = (pdf_exporter.proxies.PDFField) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.PDFField";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
