// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies;

public class PDFTemplate extends pdf_exporter.proxies.PDFDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PDF_Exporter.PDFTemplate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TemplateName("TemplateName"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		FieldNamesForm_BlankForm("PDF_Exporter.FieldNamesForm_BlankForm"),
		PDFTemplate_MxObjectType("PDF_Exporter.PDFTemplate_MxObjectType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PDFTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PDF_Exporter.PDFTemplate"));
	}

	protected PDFTemplate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pDFTemplateMendixObject)
	{
		super(context, pDFTemplateMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PDF_Exporter.PDFTemplate", pDFTemplateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PDF_Exporter.PDFTemplate");
	}

	/**
	 * @deprecated Use 'PDFTemplate.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pdf_exporter.proxies.PDFTemplate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pdf_exporter.proxies.PDFTemplate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pdf_exporter.proxies.PDFTemplate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pdf_exporter.proxies.PDFTemplate(context, mendixObject);
	}

	public static pdf_exporter.proxies.PDFTemplate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pdf_exporter.proxies.PDFTemplate.initialize(context, mendixObject);
	}

	public static java.util.List<pdf_exporter.proxies.PDFTemplate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pdf_exporter.proxies.PDFTemplate> result = new java.util.ArrayList<pdf_exporter.proxies.PDFTemplate>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PDF_Exporter.PDFTemplate" + xpathConstraint))
			result.add(pdf_exporter.proxies.PDFTemplate.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of TemplateName
	 */
	public final String getTemplateName()
	{
		return getTemplateName(getContext());
	}

	/**
	 * @param context
	 * @return value of TemplateName
	 */
	public final String getTemplateName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.TemplateName.toString());
	}

	/**
	 * Set value of TemplateName
	 * @param templatename
	 */
	public final void setTemplateName(String templatename)
	{
		setTemplateName(getContext(), templatename);
	}

	/**
	 * Set value of TemplateName
	 * @param context
	 * @param templatename
	 */
	public final void setTemplateName(com.mendix.systemwideinterfaces.core.IContext context, String templatename)
	{
		getMendixObject().setValue(context, MemberNames.TemplateName.toString(), templatename);
	}

	/**
	 * @return value of FieldNamesForm_BlankForm
	 */
	public final pdf_exporter.proxies.FieldNamesForm getFieldNamesForm_BlankForm() throws com.mendix.core.CoreException
	{
		return getFieldNamesForm_BlankForm(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldNamesForm_BlankForm
	 */
	public final pdf_exporter.proxies.FieldNamesForm getFieldNamesForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pdf_exporter.proxies.FieldNamesForm result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FieldNamesForm_BlankForm.toString());
		if (identifier != null)
			result = pdf_exporter.proxies.FieldNamesForm.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FieldNamesForm_BlankForm
	 * @param fieldnamesform_blankform
	 */
	public final void setFieldNamesForm_BlankForm(pdf_exporter.proxies.FieldNamesForm fieldnamesform_blankform)
	{
		setFieldNamesForm_BlankForm(getContext(), fieldnamesform_blankform);
	}

	/**
	 * Set value of FieldNamesForm_BlankForm
	 * @param context
	 * @param fieldnamesform_blankform
	 */
	public final void setFieldNamesForm_BlankForm(com.mendix.systemwideinterfaces.core.IContext context, pdf_exporter.proxies.FieldNamesForm fieldnamesform_blankform)
	{
		if (fieldnamesform_blankform == null)
			getMendixObject().setValue(context, MemberNames.FieldNamesForm_BlankForm.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FieldNamesForm_BlankForm.toString(), fieldnamesform_blankform.getMendixObject().getId());
	}

	/**
	 * @return value of PDFTemplate_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getPDFTemplate_MxObjectType() throws com.mendix.core.CoreException
	{
		return getPDFTemplate_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFTemplate_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getPDFTemplate_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFTemplate_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFTemplate_MxObjectType
	 * @param pdftemplate_mxobjecttype
	 */
	public final void setPDFTemplate_MxObjectType(mxmodelreflection.proxies.MxObjectType pdftemplate_mxobjecttype)
	{
		setPDFTemplate_MxObjectType(getContext(), pdftemplate_mxobjecttype);
	}

	/**
	 * Set value of PDFTemplate_MxObjectType
	 * @param context
	 * @param pdftemplate_mxobjecttype
	 */
	public final void setPDFTemplate_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType pdftemplate_mxobjecttype)
	{
		if (pdftemplate_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.PDFTemplate_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFTemplate_MxObjectType.toString(), pdftemplate_mxobjecttype.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pdf_exporter.proxies.PDFTemplate that = (pdf_exporter.proxies.PDFTemplate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PDF_Exporter.PDFTemplate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
