// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pdf_exporter.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the PDF_Exporter module
	public static boolean bDe_MxXpath(IContext context, pdf_exporter.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			return (Boolean)Core.execute(context, "PDF_Exporter.BDe_MxXpath", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_Attribute(IContext context, pdf_exporter.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PDF_Exporter.DS_Attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_First_Attribute(IContext context, pdf_exporter.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PDF_Exporter.DS_First_Attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_First_Reference(IContext context, pdf_exporter.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PDF_Exporter.DS_First_Reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_Reference(IContext context, pdf_exporter.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PDF_Exporter.DS_Reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectType> dS_RetrievableEntities(IContext context, pdf_exporter.proxies.PDFField _pDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PDFField", _pDFField == null ? null : _pDFField.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PDF_Exporter.DS_RetrievableEntities", params);
			java.util.List<mxmodelreflection.proxies.MxObjectType> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectType>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectType.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ExportPDF(IContext context, pdf_exporter.proxies.AnyObject _anyObject)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("AnyObject", _anyObject == null ? null : _anyObject.getMendixObject());
			Core.execute(context, "PDF_Exporter.IVK_ExportPDF", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_OpenAttributeMapper(IContext context, pdf_exporter.proxies.PDFField _pDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PDFField", _pDFField == null ? null : _pDFField.getMendixObject());
			Core.execute(context, "PDF_Exporter.IVK_OpenAttributeMapper", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveAttributeMapping(IContext context, pdf_exporter.proxies.PDFField _pDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PDFField", _pDFField == null ? null : _pDFField.getMendixObject());
			Core.execute(context, "PDF_Exporter.IVK_SaveAttributeMapping", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveMappings(IContext context, pdf_exporter.proxies.PDFTemplate _blankForm)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("BlankForm", _blankForm == null ? null : _blankForm.getMendixObject());
			Core.execute(context, "PDF_Exporter.IVK_SaveMappings", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_StartFieldMapping(IContext context, pdf_exporter.proxies.PDFTemplate _blankForm)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("BlankForm", _blankForm == null ? null : _blankForm.getMendixObject());
			Core.execute(context, "PDF_Exporter.IVK_StartFieldMapping", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_AttributeSelected(IContext context, pdf_exporter.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			Core.execute(context, "PDF_Exporter.OCh_AttributeSelected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_StaticValue(IContext context, pdf_exporter.proxies.PDFField _pDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PDFField", _pDFField == null ? null : _pDFField.getMendixObject());
			Core.execute(context, "PDF_Exporter.OCh_StaticValue", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_XPath_Refresh(IContext context, pdf_exporter.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			Core.execute(context, "PDF_Exporter.OCh_XPath_Refresh", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_Xpath_RetrieveType(IContext context, pdf_exporter.proxies.MxXPath _parentMxXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ParentMxXPath", _parentMxXPath == null ? null : _parentMxXPath.getMendixObject());
			Core.execute(context, "PDF_Exporter.OCh_Xpath_RetrieveType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_ClonePDFField(IContext context, pdf_exporter.proxies.PDFField _original_PDFField, pdf_exporter.proxies.PDFField _new_PDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Original_PDFField", _original_PDFField == null ? null : _original_PDFField.getMendixObject());
			params.put("New_PDFField", _new_PDFField == null ? null : _new_PDFField.getMendixObject());
			Core.execute(context, "PDF_Exporter.SUB_ClonePDFField", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_GenerateDocument(IContext context, pdf_exporter.proxies.CompleteForm _completeForm, boolean _editable, boolean _populateFields)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("CompleteForm", _completeForm == null ? null : _completeForm.getMendixObject());
			params.put("Editable", _editable);
			params.put("PopulateFields", _populateFields);
			Core.execute(context, "PDF_Exporter.SUB_GenerateDocument", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static pdf_exporter.proxies.CompleteForm sUB_NewCompleteForm(IContext context, pdf_exporter.proxies.PDFTemplate _template)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Template", _template == null ? null : _template.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PDF_Exporter.SUB_NewCompleteForm", params);
			return result == null ? null : pdf_exporter.proxies.CompleteForm.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_PrepFields(IContext context, pdf_exporter.proxies.CompleteForm _completeForm, pdf_exporter.proxies.AnyObject _anyObject)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("CompleteForm", _completeForm == null ? null : _completeForm.getMendixObject());
			params.put("AnyObject", _anyObject == null ? null : _anyObject.getMendixObject());
			Core.execute(context, "PDF_Exporter.SUB_PrepFields", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xPath_Delete_Subs(IContext context, pdf_exporter.proxies.MxXPath _parentXPath)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ParentXPath", _parentXPath == null ? null : _parentXPath.getMendixObject());
			Core.execute(context, "PDF_Exporter.XPath_Delete_Subs", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xPath_New(IContext context, pdf_exporter.proxies.PDFField _pDFField)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PDFField", _pDFField == null ? null : _pDFField.getMendixObject());
			Core.execute(context, "PDF_Exporter.XPath_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}