// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdf_exporter.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.Date;
import java.util.List;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdf_exporter.lib.PDFInjector;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Takes a PDF file, and returns a list of fields (complete with name, value, type, and parent)
 * 
 * 
 */
public class GetFieldsFromPDF extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __PDF_Form;
	private pdf_exporter.proxies.PDFDocument PDF_Form;

	public GetFieldsFromPDF(IContext context, IMendixObject PDF_Form)
	{
		super(context);
		this.__PDF_Form = PDF_Form;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.PDF_Form = __PDF_Form == null ? null : pdf_exporter.proxies.PDFDocument.initialize(getContext(), __PDF_Form);

		// BEGIN USER CODE
		//Load the pdf file
		File pdfFile = getFileFromFileDocument(PDF_Form.getMendixObject());
		PDDocument pdfDoc = PDDocument.load(pdfFile);
		
		//Get the list of fields
		List<IMendixObject> fieldList =  PDFInjector.getFieldList_MX(pdfDoc, PDF_Form, getContext());
	
		pdfDoc.close();
		
		return fieldList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetFieldsFromPDF";
	}

	// BEGIN EXTRA CODE
	private File getFileFromFileDocument(IMendixObject fileDocument) 
	{
		File fileToPull = new File( Core.getConfiguration().getTempPath().getAbsolutePath()+"/RandomFileName" + (new Date()).getTime()+ ".pdf" );
		try {
			InputStream stream = Core.getFileDocumentContent(getContext(), fileDocument);
			FileOutputStream outputStream = new FileOutputStream( fileToPull );
 
			int read = 0;
			byte[] bytes = new byte[1024];
	 
			while ((read = stream.read(bytes)) != -1) {
				outputStream.write(bytes, 0, read);
			}
			outputStream.flush();
			outputStream.close();
		} catch (Exception e) {}	
		
		return fileToPull;
		
	}
	private void setFileInFileDocument(File f, IMendixObject fileDocument) 
	{
		try {
			FileInputStream storeStream = new FileInputStream(f);
			Core.storeFileDocumentContent(this.getContext(), fileDocument, f.getName(), storeStream);
		} 
		catch (Exception e) {System.out.println(e);}
		
	}
	// END EXTRA CODE
}
