// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdf_exporter.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetPDFField_viaMxXpath extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __mxXPath;
	private pdf_exporter.proxies.MxXPath mxXPath;

	public GetPDFField_viaMxXpath(IContext context, IMendixObject mxXPath)
	{
		super(context);
		this.__mxXPath = mxXPath;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.mxXPath = __mxXPath == null ? null : pdf_exporter.proxies.MxXPath.initialize(getContext(), __mxXPath);

		// BEGIN USER CODE
		return recurseToPDFField(mxXPath);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetPDFField_viaMxXpath";
	}

	// BEGIN EXTRA CODE
	private IMendixObject recurseToPDFField(pdf_exporter.proxies.MxXPath x) throws CoreException {
		pdf_exporter.proxies.PDFField f = null;
		f= x.getPDFField_MxXPath();
		if (f != null) {
			return f.getMendixObject();
		} else
		{
			IMendixObject m = recurseToPDFField(x.getChildMxXPath_MxXPath());
			return m;
		}
		
	}
	// END EXTRA CODE
}
