// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdf_exporter.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.Date;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdf_exporter.lib.PDFInjector;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class InjectFieldNamesIntoPDF extends CustomJavaAction<Boolean>
{
	private IMendixObject __PDF_Form_In;
	private pdf_exporter.proxies.PDFDocument PDF_Form_In;
	private IMendixObject __PDF_Form_out;
	private pdf_exporter.proxies.PDFDocument PDF_Form_out;

	public InjectFieldNamesIntoPDF(IContext context, IMendixObject PDF_Form_In, IMendixObject PDF_Form_out)
	{
		super(context);
		this.__PDF_Form_In = PDF_Form_In;
		this.__PDF_Form_out = PDF_Form_out;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.PDF_Form_In = __PDF_Form_In == null ? null : pdf_exporter.proxies.PDFDocument.initialize(getContext(), __PDF_Form_In);

		this.PDF_Form_out = __PDF_Form_out == null ? null : pdf_exporter.proxies.PDFDocument.initialize(getContext(), __PDF_Form_out);

		// BEGIN USER CODE
		
		File pdfFile_In = getFileFromFileDocument(PDF_Form_In.getMendixObject());
		PDDocument pdfDoc = PDDocument.load(pdfFile_In);
		
		File pdfFile_Out = getFileFromFileDocument(PDF_Form_out.getMendixObject());
		
		PDDocument annotatedPDF = PDFInjector.annotatePDFFieldNames(pdfDoc);
		
		//Update the Mendix object with our updated pdf file
		annotatedPDF.save(pdfFile_Out);
		setFileInFileDocument(pdfFile_Out, PDF_Form_out.getMendixObject());
		
		//TEST CODE
//		annotatedPDF.save(pdfFile_In);
//		setFileInFileDocument(pdfFile_In, PDF_Form_In.getMendixObject());
		//END TEST CODE
		
		pdfDoc.close();
		annotatedPDF.close();
		//pdfFile_In.delete();
		//pdfFile_Out.delete();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "InjectFieldNamesIntoPDF";
	}

	// BEGIN EXTRA CODE
	private File getFileFromFileDocument(IMendixObject fileDocument) 
	{
		File fileToPull = new File( Core.getConfiguration().getTempPath().getAbsolutePath()+"/RandomFileName" + (new Date()).getTime()+ ".pdf" );
		try {
			InputStream stream = Core.getFileDocumentContent(getContext(), fileDocument);
			FileOutputStream outputStream = new FileOutputStream( fileToPull );
 
			int read = 0;
			byte[] bytes = new byte[1024];
	 
			while ((read = stream.read(bytes)) != -1) {
				outputStream.write(bytes, 0, read);
			}
			outputStream.flush();
			outputStream.close();
		} catch (Exception e) {}	
		
		return fileToPull;
		
	}
	private void setFileInFileDocument(File f, IMendixObject fileDocument) 
	{
		try {
			FileInputStream storeStream = new FileInputStream(f);
			Core.storeFileDocumentContent(this.getContext(), fileDocument, f.getName(), storeStream);
		} 
		catch (Exception e) {System.out.println(e);}
		
	}
	// END EXTRA CODE
}
