// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdf_exporter.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class RetrieveDateValueByAttribute extends CustomJavaAction<java.util.Date>
{
	private IMendixObject sourceObj;
	private String attributeName;

	public RetrieveDateValueByAttribute(IContext context, IMendixObject sourceObj, String attributeName)
	{
		super(context);
		this.sourceObj = sourceObj;
		this.attributeName = attributeName;
	}

	@Override
	public java.util.Date executeAction() throws Exception
	{
		// BEGIN USER CODE
		return sourceObj.getValue(this.getContext(), attributeName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "RetrieveDateValueByAttribute";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
