// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdf_exporter.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class SetValueByAttribute extends CustomJavaAction<String>
{
	private IMendixObject targetObj;
	private String memberName;
	private String value;

	public SetValueByAttribute(IContext context, IMendixObject targetObj, String memberName, String value)
	{
		super(context);
		this.targetObj = targetObj;
		this.memberName = memberName;
		this.value = value;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		targetObj.setValue(this.getContext(), memberName, value);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetValueByAttribute";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
